import {pool} from '../config/db.js'; import {generateOrderId} from '../utils/generateOrderId.js'; import {ORDER_STATUSES} from '../utils/orderStatus.js';
export async function create(req,res){const {items,shippingAddress,paymentMethod='COD',couponCode=''}=req.body;let {deliveryFee}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({message:'Cart is empty'});const conn=await pool.getConnection();try{await conn.beginTransaction();let subtotal=0;const finalItems=[];for(const item of items){const [r]=await conn.query('SELECT * FROM products WHERE id=? AND active=1 FOR UPDATE',[item.product_id]);if(!r.length||r[0].stock<item.quantity)throw new Error(`Insufficient stock for ${item.name||'product'}`);const p=r[0],qty=Number(item.quantity);const price=Number(p.discount_price||p.price);subtotal+=price*qty;finalItems.push({p,qty,price})}
    deliveryFee = 0;
    let discount=0;if(couponCode){const [c]=await conn.query('SELECT * FROM coupons WHERE code=? AND active=1 AND (expires_at IS NULL OR expires_at>=NOW())',[couponCode.toUpperCase()]);if(!c.length)throw new Error('Coupon is invalid or expired');discount=c[0].type==='percent'?subtotal*Number(c[0].value)/100:Number(c[0].value)}
    const total=Math.max(0,subtotal+Number(deliveryFee)-discount);const orderId=generateOrderId();const [o]=await conn.query('INSERT INTO orders(order_number,user_id,subtotal,delivery_fee,discount,total,payment_method,payment_status,status,shipping_address) VALUES(?,?,?,?,?,?,?,?,?,?)',[orderId,req.user.id,subtotal,deliveryFee,discount,total,paymentMethod,paymentMethod==='COD'?'pending':'pending','placed',JSON.stringify(shippingAddress||{})]);for(const x of finalItems){await conn.query('INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES(?,?,?,?)',[o.insertId,x.p.id,x.qty,x.price]);await conn.query('UPDATE products SET stock=stock-?,sales_count=sales_count+? WHERE id=?',[x.qty,x.qty,x.p.id])}await conn.commit();res.status(201).json({id:o.insertId,order_number:orderId,subtotal,delivery_fee:Number(deliveryFee),discount,total,status:'placed'})}catch(e){await conn.rollback();res.status(400).json({message:e.message})}finally{conn.release()}}
export async function mine(req,res){const [rows]=await pool.query(`SELECT o.*, COALESCE(s.item_count,0) item_count, s.items_summary FROM orders o LEFT JOIN (SELECT oi.order_id, COUNT(*) item_count, GROUP_CONCAT(CONCAT(p.name,' (x',oi.quantity,')') SEPARATOR ', ') items_summary FROM order_items oi JOIN products p ON p.id=oi.product_id GROUP BY oi.order_id) s ON s.order_id=o.id WHERE o.user_id=? ORDER BY o.created_at DESC`,[req.user.id]);res.json(rows)}
export async function all(req,res){const {search='',status=''}=req.query;const params=[];let where='WHERE 1=1';if(search){where+=' AND (o.order_number LIKE ? OR u.name LIKE ? OR u.email LIKE ?)';const s=`%${search}%`;params.push(s,s,s)}if(status){where+=' AND o.status=?';params.push(status)}const [rows]=await pool.query(`SELECT o.*,u.name customer_name,u.email FROM orders o JOIN users u ON u.id=o.user_id ${where} ORDER BY o.created_at DESC`,params);res.json(rows)}
export async function details(req,res){const [o]=await pool.query('SELECT o.*,u.name customer_name,u.email,u.phone,u.address customer_address,u.city customer_city FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?',[req.params.id]);if(!o.length)return res.status(404).json({message:'Order not found'});if(req.user.role!=='admin'&&o[0].user_id!==req.user.id)return res.status(403).json({message:'You are not allowed to view this order'});const [items]=await pool.query('SELECT oi.*,p.name,p.image FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?',[req.params.id]);res.json({...o[0],items})}
export async function updateStatus(req,res){if(!ORDER_STATUSES.includes(req.body.status))return res.status(400).json({message:'Invalid status'});const [r]=await pool.query('UPDATE orders SET status=? WHERE id=?',[req.body.status,req.params.id]);if(!r.affectedRows)return res.status(404).json({message:'Order not found'});res.json({message:'Order status updated',status:req.body.status})}
